services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-example}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mydb}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    ports:
      - "3306:3306"
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:latest
    restart: always
    container_name: adminer
    profiles: ["adminer"]
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: ${ADMINER_DEFAULT_SERVER:-mysql}
      ADMINER_DESIGN: ${ADMINER_DESIGN:-konya}
    depends_on:
      - mysql
    networks:
      - mysql-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    profiles: ["phpmyadmin"]  # Optional profile
    ports:
      - "8081:80"
    environment:
      PMA_HOST: ${PMA_HOST:-mysql}
      PMA_USER: ${PMA_USER:-user}
      PMA_PASSWORD: ${PMA_PASSWORD:-password}
    depends_on:
      - mysql
    networks:
      - mysql-network

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      device: ./mysql_data
      o: bind

networks:
  mysql-network:
    driver: bridge
