services:
  valkey:
    image: valkey/valkey:9.1.2
    container_name: valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    networks:
      - valkey_network

volumes:
  valkey_data:
    name: ${VOLUME_PREFIX:-valkey}_valkey_data

networks:
  valkey_network:
    driver: bridge
