services:
  postgres-pgvector:
    image: pgvector/pgvector:pg17
    container_name: postgres-pgvector
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network
    restart: unless-stopped
    # command: >
    #   bash -c "docker-entrypoint.sh postgres
    #   -c shared_preload_libraries='pgvector'
    #   -c pgvector.enabled=on"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-myuser} -d ${POSTGRES_DB:-mydatabase}"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
  pgadmin:
    image: elestio/pgadmin:latest
    container_name: pgadmin
    profiles: ["pgadmin"]
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-adminpassword}
    depends_on:
      - postgres-pgvector
    ports:
      - "5433:80"
    networks:
      - postgres-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: ./postgres_data
      o: bind

networks:
  postgres-network:
    driver: bridge