services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb-network
    command: ["mongod", "--auth", "--bind_ip_all"]
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand({ ping: 1 })'"]
      interval: 5s
      timeout: 5s
      retries: 10

  mongo-express:
    image: mongo-express:latest
    restart: always
    container_name: mongo-express
    profiles: ["mongo-express"]
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD:-example}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL:-mongodb://root:example@mongo:27017/}
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
    networks:
      - mongodb-network
  
volumes:
  mongodb_data:
    driver: local
    driver_opts:
      type: none
      device: ./mongodb_data
      o: bind

networks:
  mongodb-network:
    driver: bridge