[agent]
  interval = "10s"
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"
[[inputs.cpu]]
  percpu = true
  totalcpu = true